name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [debug]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
        
      - name: Build
        run: |
          mkdir -p build
          ./scripts/cmake_build_2022.bat ${{matrix.configuration}} 